!!python/object/apply:collections.OrderedDict
- - - gradient_steps
    - 10
  - - learning_rate
    - 0.0005
  - - learning_starts
    - 100
  - - n_timesteps
    - 100000
  - - policy
    - MlpPolicy
  - - train_freq
    - 10
