settings = {'batch_size': 100,
            'test_every': 1,
            'num_batches': 100,
            'num_minibatches': 100,
            'num_epochs': 1000,
            'time_step': 0.05,
            'sections_num': 1,
            'lr_start': 1e-4,
            'lr_end': 1e-6,
            'weight_decay': 1e-5,
            'es_gain': 1000,
            'h_dim': 64 * 7,
            'starting_point': [0, 0, 0, 0],
            'data_dir': 'tmp/data',
            'ckpt_dir': 'tmp/current',
            'seed': 20,
            'eff_datasampling': 1,
            'buffer_length': 10,
            'buffer_length_max': 10,
            'num_dof': 4,
            'data_source': 'database',
            'database_name': '/home/gonz_jm/Documents/thesis_workspace/databases'
                             '/database_150pts_10buff_fixed',
            'table_name': 'data_scrambled',
            'reload': True,
            'save': True
            }

# settings = {'batch_size': 175,
#             'test_every': 10,
#             'num_batches': 11,
#             'num_minibatches': 45,
#             'num_epochs': 1000,
#             'time_step': 0.05,
#             'sections_num': 1,
#             'lr_start': 5e-4 * 2,
#             'lr_end': 1e-6,
#             'es_gain': 10,
#             'h_dim': 64 * 10,
#             'starting_point': [0, 0, 0, 0],
#             'data_dir': 'tmp/data',
#             'ckpt_dir': 'tmp/current',
#             'seed': 10,
#             'data_source': 'database',
#             'database_name': 'Lagranx/databases/database_75_pts',
#             'table_name': 'data_scrambled',
#             'reload': True,
#             'save': True
#             }

# settings = {'batch_size': 100,
#             'test_every': 1,
#             'num_batches': 100,
#             'num_minibatches': 100,
#             'num_subbatches': 1,
#             'num_epochs': 1000,
#             'time_step': 0.05,
#             'sections_num': 1,
#             'lr_start': 1e-3,
#             'lr_end': 1e-6,
#             'es_gain': 10,
#             'h_dim': 128 * 5,
#             'starting_point': np.array([0, 0, 0, 0],
#                                        dtype=np.float32),
#             'data_dir': 'tmp/data',
#             'ckpt_dir': 'tmp/current',
#             'seed': 0,
#             'reload': False,
#             'save': True,
#             'generalize': True,
#             }

# settings = {'batch_size': 1000,
#             'test_every': 1,
#             'num_batches': 1,
#             'num_minibatches': 1000,
#             'num_subbatches': 1,
#             'num_epochs': 10000,
#             'time_step': 0.05,
#             'data_size': 1000 * 100,
#             'sections_num': 1,
#             'lr_start': 1e-3,
#             'lr_end': 1e-4,
#             'es_gain': 10,
#             'h_dim': 128 * 5,
#             'starting_point': np.array([3 * np.pi / 7,
#                                         3 * np.pi / 4, 0, 0],
#                                        dtype=np.float32),
#             'data_dir': 'tmp/data',
#             'ckpt_dir': 'tmp/current',
#             'seed': 0,
#             'reload': True,
#             'save': True,
#             'generalize': True,
#             }
