import numpy as np

settings = {'batch_size': 1000,
            'test_every': 1,
            'num_batches': 1,
            'num_minibatches': 1000,
            'num_subbatches': 1,
            'num_epochs': 10000,
            'time_step': 0.05,
            'data_size': 1000 * 100,
            'lr_start': 1e-3,
            'lr_end': 1e-4,
            'es_gain': 10,
            'h_dim': 128 * 5,
            'starting_point': np.array([3 * np.pi / 7,
                                        3 * np.pi / 4, 0, 0],
                                       dtype=np.float32),
            'data_dir': 'tmp/data',
            'ckpt_dir': 'tmp/current',
            'seed': 0,
            'reload': True,
            'save': True,
            'generalize': True,
            }
