TestEnvironment-v1:
  n_timesteps: 80000
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-3
#  env_wrapper: stable_baselines3.common.monitor.Monitor
#  vec_env_wrapper: stable_baselines3.common.vec_env.DummyVecEnv